# Generated by Django 5.2.5 on 2025-08-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
